### ISSUE TITLE
Training dataset

### ISSUE THREAD

**Issue by GanggangDong** [tim-dav/cnn-sar-despeckle#1]
Hi, how to get access to the training dataset? Would you like to share us a sopy of dataset?

**Comment by tim-dav** [comment]
Hi Ganggang, the training set is rather large so hosting it becomes an issue. Further, it is very content-specific (volcanoes only). You should be able to create your own by downloading Sentinel level 1 (SLC) products and using the tif2intensity and batcher tools within the repository. Hope this helps.
